import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const COLORS = ["#0f766e", "#2563eb", "#d97706", "#dc2626", "#7c3aed"];
const number = (item) => Number(item?.count ?? item?.complaints ?? item?.value ?? 0);

function ChartsSection({ data }) {
  const trend = data.complaintTrend.map((item) => ({ label: item.date || item.day, complaints: Number(item.complaints ?? item.count ?? 0), resolved: Number(item.resolved ?? 0) }));
  const status = data.complaintStatus.map((item) => ({ name: item.status || item.name, value: number(item) }));
  const zones = data.zones.map((item) => ({ name: item.zone || "Unknown", complaints: number(item), resolved: Number(item.resolved ?? 0) }));
  const staff = data.staffPerformance.map((item) => ({ name: item.staffName || item.name, resolved: Number(item.resolved ?? item.completed ?? item.count ?? 0) }));
  const tooltip = { contentStyle: { backgroundColor: "#102a2a", border: "1px solid #285654", borderRadius: "7px", color: "#f0fdfa" } };
  return <section className="charts-section"><div className="chart-panel chart-wide"><div className="chart-heading"><div><span className="report-eyebrow">Volume and throughput</span><h2>Complaint and resolution trends</h2></div><span>Historical view</span></div><ResponsiveContainer width="100%" height={310}><AreaChart data={trend}><defs><linearGradient id="complaintFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#0f766e" stopOpacity={.3} /><stop offset="95%" stopColor="#0f766e" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#e2ecea" /><XAxis dataKey="label" stroke="#78908e" /><YAxis stroke="#78908e" /><Tooltip {...tooltip} /><Legend /><Area type="monotone" dataKey="complaints" stroke="#0f766e" fill="url(#complaintFill)" strokeWidth={2} /><Line type="monotone" dataKey="resolved" stroke="#d97706" strokeWidth={2} /></AreaChart></ResponsiveContainer></div><div className="chart-panel"><div className="chart-heading"><div><span className="report-eyebrow">Portfolio health</span><h2>Complaint status</h2></div></div><ResponsiveContainer width="100%" height={285}><PieChart><Pie data={status} dataKey="value" nameKey="name" innerRadius={62} outerRadius={94} paddingAngle={3}>{status.map((entry, index) => <Cell key={entry.name} fill={COLORS[index % COLORS.length]} />)}</Pie><Tooltip {...tooltip} /><Legend /></PieChart></ResponsiveContainer></div><div className="chart-panel"><div className="chart-heading"><div><span className="report-eyebrow">Team output</span><h2>Staff performance</h2></div></div><ResponsiveContainer width="100%" height={285}><BarChart data={staff} layout="vertical" margin={{ left: 12, right: 15 }}><CartesianGrid strokeDasharray="3 3" stroke="#e2ecea" /><XAxis type="number" stroke="#78908e" /><YAxis type="category" dataKey="name" width={90} stroke="#78908e" /><Tooltip {...tooltip} /><Bar dataKey="resolved" fill="#2563eb" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer></div><div className="chart-panel chart-wide"><div className="chart-heading"><div><span className="report-eyebrow">Geographic view</span><h2>Zone analysis</h2></div></div><ResponsiveContainer width="100%" height={285}><BarChart data={zones}><CartesianGrid strokeDasharray="3 3" stroke="#e2ecea" /><XAxis dataKey="name" stroke="#78908e" /><YAxis stroke="#78908e" /><Tooltip {...tooltip} /><Legend /><Bar dataKey="complaints" fill="#0f766e" radius={[5, 5, 0, 0]} /><Bar dataKey="resolved" fill="#d97706" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div></section>;
}

export default ChartsSection;
